spring:
  profiles:
    active: dev
  session:
    timeout: 1800 # 30 minutes in seconds

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        name: JSESSIONID
        http-only: true
        same-site: Strict
